name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build APK
        run: |
          ./gradlew assembleRelease
          mv app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/build

- name: Setup Gradle  
  run: ./gradlew clean
